<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixelEngine.Base\PixelEngine.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Content\SampleVRAM\batch\1.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\10.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\11.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\12.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\13.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\14.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\15.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\2.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\3.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\4.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\5.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\6.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\7.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\8.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\batch\9.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\colors.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\SampleVRAM\kc.ram">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\SampleVRAM\batch\kid_walk\" />
  </ItemGroup>

</Project>
